### ISSUE TITLE
Need help. `make rl` doesn't work.

### ISSUE THREAD

**Issue by ghost** [fgolemo/cl-workshop-cvpr21-docker#14]
I followed the instruction in the README.md and tried to run `make rl` command, but it didn't work.

Here's the error messages I got.
```sh
echo "=== RUNNING RL TRACK"
=== RUNNING RL TRACK
python main.py --mode rl # this will take a bit
/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/torchvision/transforms/transforms.py:257: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
=== RUNNING RL TRACK
2021-04-07:13:40:09,608 INFO     [/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/settings/base/setting.py:550] Will load the options for setting <class 'sequoia.settings.active.continual.incremental.incremental_rl_setting.IncrementalRLSetting'> from the file at path rl_track.yaml.
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    run_rl_track(get_method_rl())
  File "main.py", line 31, in run_rl_track
    return run_track(method, IncrementalRLSetting, "rl_track.yaml")
  File "main.py", line 19, in run_track
    setting = SettingProxy(setting, yamlfile)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/client/setting_proxy.py", line 84, in __init__
    self.__setting = setting_type.load_benchmark(setting_config_path)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/settings/base/setting.py", line 569, in load_benchmark
    setting = cls.load(path=benchmark, drop_extra_fields=drop_extras)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 217, in load
    return cls.load_yaml(path, drop_extra_fields=drop_extra_fields, **kwargs)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 283, in load_yaml
    return cls.load(path, load_fn=load_fn, drop_extra_fields=drop_extra_fields, **kwargs)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 244, in load
    return cls._load(path, load_fn=load_fn, drop_extra_fields=drop_extra_fields, **kwargs)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 251, in _load
    return cls.from_dict(d, drop_extra_fields=drop_extra_fields)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 152, in from_dict
    return from_dict(cls, obj, drop_extra_fields=drop_extra_fields)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/simple_parsing/helpers/serialization/serializable.py", line 509, in from_dict
    instance = cls(**init_args)  # type: ignore
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/settings/base/setting_meta.py", line 70, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 49, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "<string>", line 36, in __init__
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/settings/active/continual/incremental/incremental_rl_setting.py", line 55, in __post_init__
    super().__post_init__(*args, **kwargs)
  File "/home/kunhee/miniconda3/envs/clcomp21/lib/python3.8/site-packages/sequoia/settings/active/continual/continual_rl_setting.py", line 323, in __post_init__
    raise RuntimeError(
RuntimeError: Passed number of tasks 0 doesn't match the number of tasks deduced from the task schedule (8)
make: *** [Makefile:7: rl] Error 1
```

**Comment by fgolemo** [comment]
@lebrice ^

**Comment by LilioISnotAfox** [comment]
Have the same problem!

**Comment by lebrice** [comment]
Hey all, I'll push a fix soon, but in the meantime, simply add a `nb_tasks: 8` in rl_track.yaml, that should do it.

**Comment by lebrice** [comment]
@fgolemo  @LilioISnotAfox  This should be fixed now! Closing this, if that's alright with you.
